
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import Downloader

current_path = os.getcwd()

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(fr"{current_path}\assets\frame0")
Downloader.get_all_configs()


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def download():
    Downloader.paste_url()


def change_path():
    new_path = Downloader.choose_local_path()
    Downloader.set_path(new_path)


window = Tk()

window.geometry("500x700")
window.configure(bg = "#404040")


canvas = Canvas(
    window,
    bg = "#404040",
    height = 700,
    width = 500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    #command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=10.0,
    y=116.0,
    width=480.0,
    height=60.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=download,
    relief="flat"
)
button_2.place(
    x=10.0,
    y=24.0,
    width=80.0,
    height=70.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=change_path,
    relief="flat"
)
button_3.place(
    x=100.0,
    y=24.0,
    width=80.0,
    height=70.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    #command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=410.0,
    y=24.0,
    width=80.0,
    height=70.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    #command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=59.0,
    y=0.0,
    width=50.0,
    height=19.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    #command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=10.0,
    y=0.0,
    width=50.0,
    height=19.0
)

canvas.create_rectangle(
    -1.0,
    99.0,
    500.0,
    100.00004577636719,
    fill="#636363",
    outline="")
window.resizable(False, False)
window.mainloop()